### ISSUE TITLE
Return value of init() not returning

### ISSUE THREAD

**Issue by RobErskine** [oberonamsterdam/craft-manytomany#1]
Hey there,

Great work on porting this over to Craft 3. Really saving my butt with a personal project. 

I found your fork on Packagist: https://packagist.org/packages/oberonamsterdam/craft-manytomany

After running composer install and trying to install the plugin, I get the following error: 
```
*Internal Server Error*

Return value of OberonAmsterdam\ManyToMany\Plugin::init() must be an instance of OberonAmsterdam\ManyToMany\void, none returned
```

Is there anyway to install your fork? Or do we need to wait for Page 8 to merge it and put it up on Packagist?

Thanks for your help,
Rob

**Comment by jariz** [comment]
@Wiejeben: 60e3ede6f61601552d133e045e23cad5b142d5de should probably be reverted.

**Comment by Wiejeben** [comment]
Yeah I think we have given Page 8 enough time to respond (https://github.com/page-8/craft-manytomany/pull/10), I sort of forgot to update the release on Packagist.

I'll make sure to publish the latest version on our Packagist tomorrow!

**Comment by RobErskine** [comment]
Awesome! Thank you guys. I'll be sure to let you know how I make out after you've published.

**Comment by Wiejeben** [comment]
The error thrown is caused by the return type `void` not being supported in PHP 7.0. Installing v1.1.0 should fix this.

**Comment by dbismut** [comment]
I'm just playing with Craft 3 and was really interested in Page 8 plugin. Happy to see that someone already did the heavy lifting porting it. Thanks!!!
